apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mf8a
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-wdye-tenant/integ-app-memm/hacbs-test-project-mf8a@sha256:5e00244a378b95654dc1d3ee78baa056ef879184d9b4e8a6ab30660073818474
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
